sudo: required
dist: xenial
language: node_js
node_js: 8.9.0
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_a6f8c23ee827_key -iv $encrypted_a6f8c23ee827_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- sudo apt-get -y install python3-pip python-dev
- sudo pip3 install -U setuptools
- sudo pip3 install -U virtualenvwrapper
- python3 -V
- pip3 -V
install:
- pip3 install -r requirements.txt
- npm install
- git clone --depth 1 "https://${GH_REF}" --branch=master generate
- git clone --depth 1 "https://${GH_REF}" --branch=source source
- chmod 600 ~/.ssh/id_rsa
script:
- git pull
- cd source && git pull
- cd .. && python3 main.py $GITHUB_TOKEN
after_script:
- git config user.name "Hzzone"
- git config user.email "Hzzone@outlook.com"
- cd generate && git add -A && git commit -m "update" && git push --force "https://$GITHUB_TOKEN@${GH_REF}"
  master:master
- ssh ubuntu@hzzone.me -o StrictHostKeyChecking=no 'ls'
env:
  global:
  - GH_REF: github.com/Hzzone/hzzone.github.io.git
branches:
  only:
  - source
  - dev
git:
  depth: 1
