sudo: required
dist: xenial
language: node_js
node_js: 8.9.0
cache:
  directories:
    - node_modules

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V

install:
  - pip3 install -r requirements.txt
  - npm install
  - git clone --depth 1 "https://${GH_REF}" --branch=master generate
  - git clone --depth 1 "https://${GH_REF}" --branch=source source

script:
  - git pull
  - cd source && git pull
  - cd .. && python3 main.py $GITHUB_TOKEN

after_script:
  # 部署
  - git config user.name "Hzzone"
  - git config user.email "Hzzone@outlook.com"
  - cd generate && git push --force "https://$GITHUB_TOKEN@${GH_REF}" master:master
  # - cd generate && ls

env:
 global:
   # Github Pages
   - GH_REF: "github.com/Hzzone/hzzone.github.io.git"

# safelist
branches:
  only:
  - source
  - dev

git:
  depth: 1