sudo: required
dist: xenial
language: node_js
node_js: 8.9.0
python: 3.6
cache:
  directories:
    - node_modules

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V

install:
  - pip3 install -r requirements.txt
  - npm install package.json
  - git clone --depth 1 https://github.com/Hzzone/hzzone.github.io.git --branch=master generate

script:
  - python3 main.py

# safelist
branches:
  only:
  - source
  - dev

git:
  depth: 1